apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-4vwp
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0018-tenant/tkrw-pr712-0075-0018-app/devfile-sample-4vwp@sha256:2c65d0fca8fbec1f4ae8a3558ac599061f8f9be72675d19158444913fa2e8a07
        name: my-nodejs
        resources: {}
status: {}
